### ISSUE TITLE
Support accessibility drag/drop

### ISSUE THREAD

**Issue by GCheung55** [heroku/ember-sortable#103]
It would be very helpful to add accessibility support.

Here's a reference guide https://dev.opera.com/articles/accessible-drag-and-drop/

**Comment by jgwhite** [comment]
Hi @GCheung55. This is an excellent idea. Would you be interested in working on a PR to implement it? I’m a little short on development time right now but I can help out in any way you need. Let me know what you think :)

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it. Note that we have added some notes on accessibility to the README.

Please feel free to re-open if you'd like to resume the conversation.
