### ISSUE TITLE
Sortable not working in chrome version 56

### ISSUE THREAD

**Issue by Sureshowler** [heroku/ember-sortable#133]
The elements are misplaced after sorting....Refer this link for source code...https://github.com/jgwhite/ember-sortable/issues/132

**Comment by Sureshowler** [comment]
Hi @acburdine ... The problem is only in windows... Could you provide a workaround ASAP....

**Comment by acburdine** [comment]
@Sureshowler sorry to ask for more - could you provide a screenshot as to what you're experiencing? I will try and get this looked at today but a screenshot would let me know what to look for. Thanks!

**Comment by Sureshowler** [comment]
Hi @acburdine .... 
I explain with screenshot

1.This is the initial page before sorting..
<img width="960" alt="bug1" src="https://cloud.githubusercontent.com/assets/8970055/23472116/d9a42dc8-fed1-11e6-9ce0-7c8539653a2d.png">

2.After the second element is dragged out of the top edge of sortable container...The first item of container is hidden ..

<img width="960" alt="bug2" src="https://cloud.githubusercontent.com/assets/8970055/23472220/21531030-fed2-11e6-95dc-26a2264a2ac1.png">

3.After the second element is swapped with first item... The elements are moved a little bit up....

<img width="960" alt="bug3" src="https://cloud.githubusercontent.com/assets/8970055/23472271/4c022280-fed2-11e6-9d1e-2023b3ebe088.png">


Here is the html for the (3) image

<ul id="ember446" class="ember-view" style="
    background: green;
"><li id="ember460" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">0 dad</li>

</li><li id="ember458" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">1 boy</li>

</li><li id="ember462" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">2 fox</li>

</li><li id="ember464" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">3 eagle</li>

</li><li id="ember466" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">4 dog</li>

</li><li id="ember468" class="ember-view sortable-item" style="transform: translateY(-24px);">      <li class="handle" style="touch-action: none;">5 frog</li>

</li>
</ul>

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
