### ISSUE TITLE
During dragging cursor should stay the same

### ISSUE THREAD

**Issue by estshy** [heroku/ember-sortable#134]
During dragging cursor should stay the same. Currently it's being changed based on element under mouse which is misleading for the user. We should put invisible layer on top of everything before starting dragging to block pointer events.

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
