### ISSUE TITLE
Any way to programmatically move items?

### ISSUE THREAD

**Issue by okachynskyy** [heroku/ember-sortable#141]
Together with drag and drop I want to add a buttons with arrows for swapping two items with the similar animation.
Can you suggest the right way to implement this behavior?

**Comment by ccarterc** [comment]
There is a test helper which you could probably leverage:
```
import './ember-sortable/test-helpers';

drag('mouse', 'ul li:nth-child(1)', function(){
  return {dy: 50, dx: 50};
});
```
This assumes you are in the test directory though, so you will likely have to change path a bit for the import.

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
