### ISSUE TITLE
How to disable dragging for some items? E.g. first or last?

### ISSUE THREAD

**Issue by okachynskyy** [heroku/ember-sortable#142]

**Comment by miguelcobain** [comment]
I think it would be very handy to have a `disabled` option that would disable dragging support if true.

**Comment by jgwhite** [comment]
I’d suggest doing something like:

```hbs
{{#sortable-group tagName="ul" onChange="reorderItems" as |group|}}
  <li>
    {{model.items.firstObject.name}}
  </li>
  {{#each (slice 1 -1 model.items) as |item|}}
    {{#sortable-item tagName="li" model=item group=group handle=".handle"}}
      {{item.name}}
      <span class="handle">&varr;</span>
    {{/sortable-item}}
  {{/each}}
  <li>
    {{model.items.lastObject.name}}
  </li>
{{/sortable-group}}
```

(In this example using [`slice` from ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers#slice).

**Comment by miguelcobain** [comment]
@jgwhite that would be a workaround for "disabling" the first and last items. However, in my use case we need to disable the form temporarily (e.g while saving) and then enabling it again.
A disable property should be straightforward (I think) and very helpful.

Would you be open to a PR for that feature?

**Comment by jgwhite** [comment]
@miguelcobain certainly :)

**Comment by Duder-onomy** [comment]
This sounds totally rad. 
I also would like to disable the entire `sortable-group` while some other work is happening.

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
