### ISSUE TITLE
Add a configurable OVERSHOOT property for test helper (reorder)

### ISSUE THREAD

**Issue by BnitoBzh** [heroku/ember-sortable#143]
I made different tests with the reorder test helper.
In some case, the reordering works correctly, but in some other cases it doesn't works ..
I tried to update the "OVERSHOOT" value, and where initialy the test failed, with a value to 20 it works.

I think it's a good idea to allow to override the value directly in the reorder function by passing a new attribute.

Or, in order to prevent breaking change, by change the dy and dx calculation like this :

const OVERSHOOT = 2;
let dx = targetElement.offset().left - OVERSHOOT - element.offset().left;
let dy = targetElement.offset().top - OVERSHOOT - element.offset().top;

TO

const OVERSHOOT = 1.1;
let dx = targetElement.offset().left - OVERSHOOT * element.offset().left;
let dy = targetElement.offset().top - OVERSHOOT * element.offset().top;

This change allow a best rounding errors management.

Should i make a pull request ?

**Comment by BnitoBzh** [comment]
const OVERSHOOT = 1.05; is better ...

**Comment by pboutin** [comment]
I had some inconsistencies in my tests as well. Changing the `OVERSHOOT` fixed it for me as well.

I suggest having `reorder(app, itemSelector, resultSelectors, options)` as the new contract (having the overshoot and the mode into an option hash with defaults.

I can open a PR if you want.

**Comment by jgwhite** [comment]
@pboutin a PR would be awesome. Thank you!

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
