### ISSUE TITLE
Actions (click events) doesn't works for IPad device.

### ISSUE THREAD

**Issue by Allariel** [heroku/ember-sortable#145]
Hello guys!
I uses the ember sortable (1.9.3 version) for my application.
He breaks the functionality of ember actions (click events) on IPad device.

Steps to reproduce:
1. Add some controller with `test` action.
1. Add the sortable component to hbs of controller.
2. Add action (`<div {{action "test"}}>test</div>`) to inner DOM node of the sortable item component.

Current result: The test action doesn't called by click on node.
Expected result: The test action should be called by click on node.

I tried to comment some code (please see it below) and this works for me, but I'm not sure if this solution is good:

```
  _primeDrag(event) {
    let handle = this.get('handle');

    if (handle && !$(event.target).closest(handle).length) {
      return;
    }

    //event.preventDefault();
    //event.stopPropagation();

    this._startDragListener = event => this._startDrag(event);

    this._cancelStartDragListener = () => {
      $(window).off('mousemove touchmove', this._startDragListener);
    };

    $(window).one('mousemove touchmove', this._startDragListener);
    $(window).one('click mouseup touchend', this._cancelStartDragListener);
  },
```

Could you help me please?

**Comment by Allariel** [comment]
I use other selector for handle property and this fixed this issue.

**Comment by Allariel** [comment]
Hello guys! I investigate this issue and found out that we can comments only `event.preventDefault();` in `_primeDrag` function, because this uses only for text selection. We can prevent selection with help css.
What you think about this?

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it.

Please feel free to re-open if you'd like to resume the conversation.
