### ISSUE TITLE
The future is ember-animated

### ISSUE THREAD

**Issue by jgwhite** [heroku/ember-sortable#178]
I propose to either sunset this addon and give people a transition path to ember-animated or perhaps reimagine it as a thin wrapper atop ember-animated.

Thoughts welcome!

**Comment by joe-wroten-q2** [comment]
ember-sortable has accomplished exactly what I attempted to create in an app I'm working on in a reliable way. I'd hate to see it go, but if the plan is to sunset the addon then I'd be happy to replace what we have with a thin wrapper atop of ember-animated should that be created.

**Comment by jgwhite** [comment]
I still think this is worth exploring, but it’s a long way off so closing for now.
