### ISSUE TITLE
Replace jquery with vanilla javascript

### ISSUE THREAD

**Issue by omairvaiyani** [heroku/ember-sortable#179]
I'm happy to take on this task if you think it's achievable and desirable? On a quick skim, I couldn't see any major reasons why jquery is fundamental to the logic here.

In terms of why - I know many developers took to removing jquery to simplify their fastboot integration. I know there are ways around integrating fastboot whilst keeping jquery, but if it's doable, I think it's a worthwhile project.

**Comment by aandis** [comment]
+1

**Comment by jgwhite** [comment]
Thank you everyone for your feedback on this. Happily this was implemented in #212 by very fine fellow @nlfurniss and released as part of [1.12.2](https://www.npmjs.com/package/ember-sortable/v/1.12.2).

**Comment by omairvaiyani** [comment]
Great stuff!
