### ISSUE TITLE
How can I change the offset, so that repositioning happens earlier?

### ISSUE THREAD

**Issue by ivanvotti** [heroku/ember-sortable#183]
By default repositioning occurs as soon as the dragging element covers more than 100% of the sibling element. I'd like to change it to 50%, so that I need to overlap  just 50% of the sibling to trigger the repositioning. 

In the GIF below, the first example is what I'd like to achieve, the second one shows what happens by default:

![jul-20-2018 21-17-26](https://user-images.githubusercontent.com/1476221/43013442-5d3ae770-8c62-11e8-93c2-2953717d2881.gif)

Also you can see what I'm trying to get in this demo: http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=m7v8q5

**Comment by jgwhite** [comment]
There is currently no API for this. A PR that adds one would be welcome.
