### ISSUE TITLE
Use closure actions for 'onDragStart` & `onDragStop` drag actions

### ISSUE THREAD

**Issue by jmar910** [heroku/ember-sortable#191]
We can refactor this to use closure actions instead of action bubbling
https://github.com/heroku/ember-sortable#drag-actions

**Comment by jgwhite** [comment]
I’m inclined to leave the code and example as-is. My reasoning is that `sendAction` works with  `onDragStart="myAction"`, `onDragStart=(action "myAction")`, and `onDragStart=(action myAction)` so we continue to offer full backwards-compatibility. Though I personally prefer `onDragStart=(action myAction)`, `onDragStart=(action "myAction")` aligns better with Ember’s guides so I think we should stick with that.

Re-open if you disagree 😅
