### ISSUE TITLE
Unclean Event Registration causes onChange to trigger incrementally

### ISSUE THREAD

**Issue by fonkgoku** [heroku/ember-sortable#217]
When using ember-sortable as described in the README, the onChange action is triggered multiple times and increases by 2 for every drag event.

I created a twiddle to outline this problem:
https://ember-twiddle.com/c75a926136ccbbb68963f3c2cf4be136?openFiles=controllers.application.js%2C

To reproduce open up the console and start dragging the items. As you can see "reorder" is logged first 2 times, then 4, then 6 and so on.

This is likely due to eventListeners being applied without being removed. I was able to fix this by replacing `releaseEvents` in `mixins/sortable-item.js` with `removeEventListener` without any noticeable problems.
https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L396

I'd be happy to create a PR to address this issue. 🙂

**Comment by jgwhite** [comment]
A PR would be very welcome. Thanks for reporting!

**Comment by fonkgoku** [comment]
Merged to master, closing.
