### ISSUE TITLE
No event passed to preventClickHandler

### ISSUE THREAD

**Issue by fonkgoku** [heroku/ember-sortable#218]
In a conventional use case, I noticed `_preventClickHandler()` throwing an error:
`Cannot read property 'stopPropagation' of undefined`

You can see this happening in this Twiddle if you open up the console and start dragging items.
https://ember-twiddle.com/c75a926136ccbbb68963f3c2cf4be136?openFiles=controllers.application.js%2C

I suspect this is because no event object is passed to `_preventClickHandler()` on line 633 of `mixins/sortable-item`.
https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L633

I fixed this by passing the event like so 
```
  _preventClick() {
    const selfCancellingCallback = (event) => {
      this.element.removeEventListener(elementClickAction, selfCancellingCallback);
      this._preventClickHandler(event);
    };

    this.element.addEventListener(elementClickAction, selfCancellingCallback);
  },
```

Let me know if you need a PR for this 🙂

**Comment by jgwhite** [comment]
We’d also love a PR for this. I’ll leave it up to you whether you bundle the fix with the other issue you observed.

**Comment by fonkgoku** [comment]
Merged to master, closing.
