### ISSUE TITLE
Dropping is missing a runloop

### ISSUE THREAD

**Issue by mixonic** [heroku/ember-sortable#219]
**Describe the bug**

When dropping the [drop handler](https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L394-L402) is called, which in turn calls` _drop` which [itself sets some state](https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L617-L618).

It seems that we should have a runloop around the `set` calls at the least, or a `run.join` around the handler in general.

**To Reproduce**

`await pauseTest()` in a test suite, and try to use the drag and drop functionality. "You must have a runloop" errors will occur.

In dev/prod those errors don't come up, instead an auto-run handles the flushing of the queues. For ember-sortable to have determinable, consistent behavior auto-runs should be avoided. Auto-runs can also be a performance issue.

**Comment by jgwhite** [comment]
Great catch. Care to submit a PR for this? ☺️
