### ISSUE TITLE
inline `touch-action:none` not being properly applied 

### ISSUE THREAD

**Issue by froskos** [heroku/ember-sortable#230]
**Bug description**

I used the library "as it came" and found that (most recent version). Differently from the demo, I could not successfully use it to sort a list in a touch device. With mouse everything worked fine.

**Steps to Reproduce**

1. Create a sortable list in which the sortable items DO get a value for the `handle` attribute. The list must have at least 2 elements.
2. Test drag&drop sorting with a device with a mouse. It works fine.
3. Repeat the test in the touch device, trying to move the nth element (n > 1) by touching the defined handle, keeping the touch, and moving it. It does not work
4. The message `Unable to preventDefault inside passive event listener due to target being treated as passive.` is logged at the console. The inline style `touch-action:none` given to the handle element is only applied at the first element in the list.

**Expected behavior**

Sorting at touch devices should work when a drag handle is specified for the sortable item

**Comment by froskos** [comment]
PR available:

https://github.com/heroku/ember-sortable/pull/229

**Comment by jgwhite** [comment]
Closed by #229 

Will be released as part of 1.12.5 (soon).
