### ISSUE TITLE
Drag and drop failing in touch devices

### ISSUE THREAD

**Issue by froskos** [heroku/ember-sortable#235]
**Bug description**
In touch devices using webkit browsers, no item in a sortable list can be dragged (and as a consequence neither dropped)

**To Reproduce**
1. You can simply checkout version `1.12.4` and do `ember s`. Also with new version `1.12.5`
2. Access localhost:4200 and interact with the demo in a device matching the description above (touch device + webkit browsers)
3. Dragging is not triggered when holding touch

**Expected behavior**
In these devices drag&drop should work

**Additional context**
Probably happening in other browsers at touch devices, could not check so far.
Tested in integration with a running personal app at version 1.12.4, but also found this with new release 1.12.5 tested isolated

**Comment by froskos** [comment]
Proposed PR https://github.com/heroku/ember-sortable/pull/236

Some touch events do not come encapsulated in such a way that they must be accessed via `event.originalEvent`. The current version of the code does not provide for this. 

The proposed fix has been tested in isolation and integration, both vs versions 1.12.4 and 1.12.5

**Comment by jgwhite** [comment]
Awesome, thanks for the PR. Reviewing presently.

**Comment by froskos** [comment]
Hi @jgwhite ! Any feedback about this one? Thanks for reviewing! :)

**Comment by jgwhite** [comment]
@froskos sorry for letting this one slip! Taking another look now.

**Comment by jgwhite** [comment]
@froskos thanks for the awesome PR. I’m closing this issue for now. Feel free to re-open if you encounter more issue like this.
