### ISSUE TITLE
Make @ember/jquery a developer dependency

### ISSUE THREAD

**Issue by fran-worley** [heroku/ember-sortable#248]
Forgive me if I'm missing something but since jQuery was replaced with native javascript as part of #212, why do we still list `@ember/jquery` as a package dependency?

I note that it is still used for tests but wouldn't that just require it to be a dev dependency?

**Comment by jgwhite** [comment]
Great question.

I *think* it should be possible to make jQuery a dev dependency, but there’s still one thing that confuses me…

It looks like there is some implicit interaction with jQuery [in the test helpers that ship with ember-sortable](https://github.com/heroku/ember-sortable/blob/f42f62e73dbc45ef2bcd2263d172fdc756c1c337/addon/helpers/drag.js#L55). I don’t know exactly what this means for compatibility. These are part of our public API so we need to figure out how to make them work in a jQuery-less world too. Can we simply depend upon the new helpers in `@ember/test-helpers` or will that break older apps somehow?

**Comment by jgwhite** [comment]
I think what I’m saying is: we should figure out how to remote all jQuery-related stuff from test land too, and then expunge any mention of jQuery from the codebase.

**Comment by jgwhite** [comment]
In the meantime: I’d welcome a PR that moves `@ember/jquery` to dev dependencies as you propose 🙂

**Comment by fran-worley** [comment]
Lovely - but based on your initial comment, would that break the test helpers?

**Comment by jgwhite** [comment]
@fran-worley I honestly have no idea, but this is our chance to find out! 😅
