### ISSUE TITLE
Error with Ember-source version 3.3.0 to 3.4.8

### ISSUE THREAD

**Issue by ecoutlee-hortau** [heroku/ember-sortable#264]
After updating Ember-source to version 3.4.8, Ember sortable stopped working.
I was able make it work normally with Ember v3.2.2, but after v3.3.0 I get a console error.
I am not currently able to test with ember-source v3.5.x or above because I have other dependency breaking my app.

1. Install Ember source version 3.4.8
2. Try to drag and drop an element
3. See an error in console and all item are stuck

See the picture and the video (in .zip) of the error for more info.
![Screenshot from 2019-06-27 18-15-47](https://user-images.githubusercontent.com/46380280/60304929-e73f8a80-9908-11e9-92af-78c0a6a2a72e.png)

[error_video.zip](https://github.com/heroku/ember-sortable/files/3336837/error_video.zip)

**Comment by ecoutlee-hortau** [comment]
Ok updating to latest version fixed this issue. But I got other small bug with the latest version. Closing this issue.

**Comment by jgwhite** [comment]
Thanks for the report and the follow-up 🙂
