### ISSUE TITLE
visible drop-target

### ISSUE THREAD

**Issue by ianbale** [heroku/ember-sortable#76]
It would be nice to have a visible drop-target rather than just open up a space. Depending on what's in your list, the space alone can be unclear at times. I'm thinking that we add an additional class "drop-target" onto the item before the space and style it with something like:

.sortable-item.drop-target:after
{
    content: " ";
    display: block;
    width : 100%;
    height : 50px;
    border : 2px dashed yellow;
    background-color: #FFF8F8;
    opacity: 1;
}

In the case where the drop target is before the first item, we can add a different class "drop-target-before" and use :before CSS selector instead.

I've looked through the code and now have a reasonably good idea how most of it works. But some of it is still eluding me...

I can see how the dragged item updates its position. And that  it calls update on the group which in turn sets their positions. What I can't see is how the other item's position is calculated? Could you provide a few notes on how that works please?

**Comment by jgwhite** [comment]
Hey sorry for the slow reply (holidays). The other items get their positions from the group: https://github.com/jgwhite/ember-sortable/blob/master/addon/components/sortable-group.js#L108

**Comment by ianbale** [comment]
I've pretty much worked out how it all works. Always nice understanding someone else's code and discovering a way to do things that you'd not thought of yourself! Also a good exercise for me to understand how an ember add-on is constructed. Whilst I've done a fair bit of ember now (all very complex apps), I've not tried to create an add-on before.

I've got something 80% working now. Although I've decided I can't use :after :before since I cannot set the height of those to match the dragged element. Instead I'm inserting a DIV. That causes the element below to be moved, which means, other than the initial translate, no other translate is required in update. Instead we just move the drop-target DIV.

I've got a small tweak to do now because the drop-target DIV does appears after where the item was originally, not where it is translated to. That's easy enough to do. Next job then is to modify my fixed drop-target height / width CSS and inject the size from the dragged item. I'll send you a preview when it's done.

Then I guess I need to do away with a hard coded DIV and look at a way to replicate the dragged item, clearing any content. So, for example, in the table example, I need to insert a TR tag as a drop-target.

One other enhancement I want to make is to set some meta data on the original item to indicate that it is being dragged. That's the original data being passed in, not the date we hold internally. This is important in my use case since we have varying sizes of items, and some are very large. So I want to render the item as a fixed size "drag helper" whilst it's being dragged. It's just easier than trying to drag sort an item that's the height of the screen! I also need that smart scrolling too since my lists are way larger than the screen...

I think I'll need to use something similar in order to inject a new item into the list for my "drag into a list" requirement... But I'll look at that in the New Year. Only got a couple of hours left to work today :-)

**Comment by ianbale** [comment]
Fork here: https://github.com/ianbale/ember-sortable

Drop target working properly for vertical sorting. Horizontal messed up because it still has a fixed height/width for the drop-target rather than looking at the dragged item. Time to give up for the holidays though!

**Comment by jgwhite** [comment]
Awesome progress! Thanks so much for working on this. I also need to take a break from GitHub for the holidays but let's get this formalised into a pull request once the festivities have wound up. :santa:

**Comment by ianbale** [comment]
More updates checked into GIT. And a demo here: http://www.bale.net/ember-sortable/

The visible drop-target stuff is fully working now.

I've tried to make the new code neat, but to be honest it does need some tidying up now. My priority was to get something working quickly so I could carry on with the project I'm working on. I'll get back to it at some point and neaten it up - unless you decide you want to pull this into your project first. Not sure if you'll want to do that since I've made considerable changes to the way the items are moved about in order to make all this work...

And you can drag new items into the list. This works fine for the vertical sorting, but not for horizontal or the table - yet. I think that's because the sizing of the drop-target is fixed in the CSS at the moment, and not dynamically picked up from the sort list / drag item. I only need the vertical scrolling at the moment and fixed sizing in the CSS suits my needs. So I am probably not going to get much more done on that for now. The only change I still need for vertical scrolling is to have the ability to override the size of the dragged item so that as soon as I start to drag it is reduced in size to a manageable height since some items I am dragging can be very large - possible larger than the screen.

The other thing I really need is auto-scrolling when dragging at the top/bottom of the screen. I'm hoping that Glavin001 is going to take a look at that for you...? If so I can merge that into mine. If not, I'll pick that task up a little later. For now I need to get this into my project and carry on working on that in time to show it all off to my client on 6th Jan...

**Comment by jevanlingen** [comment]
@ianbale: Is this feature still being worked on? Would be a nice addition to this addon!

**Comment by ianbale** [comment]
@jevanlingen : It kinda got hijacked and modified to be quite specific for the client job I mentioned.

That's not to say it couldn't be made a little more generic again without too much work. I'm happy to answer any questions about the code if you want to pm me, but it's unlikely that I will work on this again any time soon. Right now I'm not even working with Ember...

**Comment by jgwhite** [comment]
This project is now being maintained by the team at @heroku.

To get the project healthy and maintainable again, we're doing a bit of spring cleaning of older issues and pull requests. This issue hasn't been touched in a while so we're closing it. Thanks for all the great ideas and discussion.

Please feel free to re-open if you'd like to resume the conversation.
